/*
 * product_add_specifics_inner_booking_details_availabilities_inner.h
 *
 * 
 */

#ifndef _product_add_specifics_inner_booking_details_availabilities_inner_H_
#define _product_add_specifics_inner_booking_details_availabilities_inner_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct product_add_specifics_inner_booking_details_availabilities_inner_t product_add_specifics_inner_booking_details_availabilities_inner_t;

#include "product_add_specifics_inner_booking_details_availabilities_inner_times_inner.h"

// Enum DAY for product_add_specifics_inner_booking_details_availabilities_inner

typedef enum  { api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_NULL = 0, api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_sunday, api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_monday, api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_tuesday, api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_wednesday, api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_thursday, api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_friday, api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_saturday } api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_e;

char* product_add_specifics_inner_booking_details_availabilities_inner_day_ToString(api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_e day);

api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_e product_add_specifics_inner_booking_details_availabilities_inner_day_FromString(char* day);



typedef struct product_add_specifics_inner_booking_details_availabilities_inner_t {
    api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_e day; //enum
    int is_available; //boolean
    list_t *times; //nonprimitive container

    int _library_owned; // Is the library responsible for freeing this object?
} product_add_specifics_inner_booking_details_availabilities_inner_t;

__attribute__((deprecated)) product_add_specifics_inner_booking_details_availabilities_inner_t *product_add_specifics_inner_booking_details_availabilities_inner_create(
    api2cart_openapi_product_add_specifics_inner_booking_details_availabilities_inner_DAY_e day,
    int is_available,
    list_t *times
);

void product_add_specifics_inner_booking_details_availabilities_inner_free(product_add_specifics_inner_booking_details_availabilities_inner_t *product_add_specifics_inner_booking_details_availabilities_inner);

product_add_specifics_inner_booking_details_availabilities_inner_t *product_add_specifics_inner_booking_details_availabilities_inner_parseFromJSON(cJSON *product_add_specifics_inner_booking_details_availabilities_innerJSON);

cJSON *product_add_specifics_inner_booking_details_availabilities_inner_convertToJSON(product_add_specifics_inner_booking_details_availabilities_inner_t *product_add_specifics_inner_booking_details_availabilities_inner);

#endif /* _product_add_specifics_inner_booking_details_availabilities_inner_H_ */

